local Sounds = {
	Notification = { SoundId = "rbxassetid://110217765141398", Volume = 1 },
	-- Hover = { SoundId = "rbxassetid://0", Volume = 0.5 },
	-- Click = { SoundId = "rbxassetid://0", Volume = 0.5 },
	-- purchase_process = { SoundId = "rbxassetid://0", Volume = 1 },
	-- purchase_completed = { SoundId = "rbxassetid://0", Volume = 1 },
    typewriter = { SoundId = "rbxassetid://147982968", Volume = 1 },
    Scary = { SoundId = "rbxassetid://129098116998483", Volume = 1 },
    Jjuuk = { SoundId = "rbxassetid://139020562647289", Volume = 1 }, -- Cartoon stretch/spring sound
	Swing = { SoundId = "rbxassetid://101467914599270", Volume = 1 },
	Hit = { SoundId = "rbxassetid://7171761940", Volume = 1}
}

return Sounds
