local Sounds = {
	Notification = { SoundId = "rbxassetid://110217765141398", Volume = 1 },
	-- Hover = { SoundId = "rbxassetid://0", Volume = 0.5 },
	-- Click = { SoundId = "rbxassetid://0", Volume = 0.5 },
	-- purchase_process = { SoundId = "rbxassetid://0", Volume = 1 },
	-- purchase_completed = { SoundId = "rbxassetid://0", Volume = 1 },
    typewriter = { SoundId = "rbxassetid://147982968", Volume = 1 },
	Scary = { SoundId = "rbxassetid://129098116998483", Volume = 1 },
}

return Sounds
